# Autogenerated wrapper script for X42Dpl_jll for aarch64-linux-gnu
export dpl_bin, dpl_lv2

using lv2_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("X42Dpl")
JLLWrappers.@declare_library_product(dpl_bin, "dpl.so")
JLLWrappers.@declare_file_product(dpl_lv2)
function __init__()
    JLLWrappers.@generate_init_header(lv2_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        dpl_bin,
        "share/lv2/dpl.lv2/dpl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        dpl_lv2,
        "share/lv2/dpl.lv2/manifest.ttl",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
